/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.javacodegeeks.patterns.templatepattern;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
